### PR TITLE
Added Molecular Weight

### PR DESCRIPTION
**Pull request by wiwalsh**
Added molecular weight and tests.

### CODE REVIEW

**Comment by MadsFoged** [comment]
Does Molecular Weight have a unit that is used in [UnitsNet](https://github.com/angularsen/UnitsNet)?
SharpFluids needs to handle the units as well, hence Im not too happy with just using a double

**Comment by wiwalsh** [comment]
It is the sum of the atomic masses (from the periodic table) for the molecule.  It has a weird units relationship.  So it can be lbm/lbm or kg/kmol, or g/mol, etc.  If you mix units you can get weird results, but it isn't typically used in that way.  Typically you go to the periodic table and use the numbers right off of that without any conversion factors independent of what units you are using.  So, representing it as a unit might be unhelpful.  

When googling, it says that the true units are a Dalton, or unified atomic mass unit.
https://www.lenntech.com/calculators/molecular/molecular-weight-calculator.htm

I am open to opinions and other options though.

**Comment by MadsFoged** [comment]
I found this: "MolarMass" in UnitsNet

Is that the same as Molecular Weight?
If it is and you implement it as that I will be fine by me

**Comment by wiwalsh** [comment]
Did some more research and I think I agree.  Updated to use unitsNet based on MolarMass  Tests pass.

**Comment by MadsFoged** [comment]
I did something wrong when I merged your commit into Master but it should work now!
Thank you for your work wiwalsh!

**Pull request merged**
